Add French translation
IgniteUI/igniteui-angular-i18n pull request #51
Opened 2021-01-22 13:15 UTC by DanielRose

With the help of some colleagues I created a translation into French. Since I'm not a native speaker myself, please excuse any errors.

2021-01-25 15:26 UTC, kdinev commented
For reviewers reference, here's the EN strings:

https://github.com/IgniteUI/igniteui-angular/tree/master/projects/igniteui-angular/src/lib/core/i18n

2021-01-25 15:57 UTC, DanielRose commented
Rebased on current master

2021-01-27 09:59 UTC, DanielRose commented
Rebased on current master

2021-01-28 11:41 UTC, Lipata requested changes
@DanielRose thank you once again for the French translation. Because we don't have a French-speaking colleague, I've just checked the changes in the PR with google translate and it only suggested me 3 things that I've listed below. I guess a those suggestions can be wrong or just an alternative, so please approve them if they are only typos or are a better fit.

2021-01-28 11:41 UTC, Lipata commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_filter_row_date_placeholder: 'Choisisser la date',
```suggestion
  igx_grid_filter_row_date_placeholder: 'Choisissez la date',
```

2021-01-28 11:41 UTC, Lipata commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_excel_select: 'Sélectionnez la colonne',
```suggestion
  igx_grid_excel_select: 'Sélectionner la colonne',
```

2021-01-28 11:41 UTC, Lipata commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_pinning_check_all_label: 'Attacher tout',
```suggestion
  igx_grid_pinning_check_all_label: 'Attache tout',
```

2021-01-29 13:27 UTC, DanielRose commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_filter_row_date_placeholder: 'Choisisser la date',
I simplified to "Choisir la date"

2021-01-29 13:27 UTC, DanielRose commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_excel_select: 'Sélectionnez la colonne',
Fixed

2021-01-29 13:28 UTC, DanielRose commented on src/i18n/FR/grid-resources.ts
> +  igx_grid_pinning_check_all_label: 'Attacher tout',
Fixed

2021-01-29 13:33 UTC, DanielRose commented
Rebased on current master

2021-01-29 13:53 UTC, IvayloG approved these changes

2021-02-01 07:55 UTC, Lipata approved these changes

2021-02-01 14:24 UTC, merged