Valadzhov/bg localization 10.2.x
IgniteUI/igniteui-angular-i18n pull request #72
Opened 2021-05-20 11:26 UTC by valadzhov

2021-05-20 19:34 UTC, dafo requested changes

2021-05-20 19:34 UTC, dafo commented on src/i18n/BG/grid-resources.ts
> +    igx_grid_emptyGrid_message: 'Таблица няма данни.',
Таблица**та** няма данни.

2021-05-20 19:34 UTC, dafo commented on src/i18n/BG/grid-resources.ts
> +    igx_grid_excel_show: 'Покажи колона',
Покажи колона**та**

2021-05-21 06:40 UTC, dafo approved these changes

2021-05-21 07:41 UTC, IvayloG requested changes
Should add the BG resource strings to the index.ts file, so these are exported as well.  Otherwise, BG strings will not be available for setup. This applies for all PRs.

2021-05-21 10:43 UTC, IvayloG approved these changes

2021-05-21 11:57 UTC, merged