Cleanup grid resources - 10.2.x
IgniteUI/igniteui-angular-i18n pull request #79
Opened 2021-05-27 12:14 UTC by IvayloG

- Cleanup excess grid resources that should not be in 10.2.x
- Use angular and igniteui-angular v10

2021-05-27 12:25 UTC, Lipata commented
Can you put @angular/core 10.2.5, which is latest v10: https://www.npmjs.com/package/@angular/core

2021-05-27 12:53 UTC, Lipata requested changes
Can you put 10.2.5 which is the latest v10: https://www.npmjs.com/package/@angular/core

2021-05-27 14:08 UTC, IvayloG commented
> Can you put 10.2.5 which is the latest v10: https://www.npmjs.com/package/@angular/core

Do we need to set it explicitly? It is the latest version actually installed and currently, it is 10.2.5

![image](https://user-images.githubusercontent.com/4296944/119840991-1bb18c00-bf0e-11eb-8889-1ab666d0d5fd.png)

2021-05-28 07:28 UTC, Lipata approved these changes

2021-05-30 11:35 UTC, merged